### ISSUE TITLE
Magic Missle - 4d4+1 != 4(d4+1)

### ISSUE THREAD

**Issue by jdell64** [thebinarypenguin/droll#1]
Hey, love the little library... I was writing one of my own, and found this...

I was thinking... this may be a niche use case, but say I wanted to use this for a d&d type app where 'magic missle' lets you roll a d4 X times, and add Y each time you roll?

At this point, I'd have to do something like:

roll(d+4)
roll(d+4)
roll(d+4)
roll(d+4)

It would be awesome to be able to do all at once. Again, niche case, but thought I'd throw this out there.

**Comment by thebinarypenguin** [comment]
Hi @jdell64 

You're right droll only supports the most basic of dice notation. It would be great to be able to support every possible use case and I remember going down that rabbit hole before I settled on just doing the basics. 

The Wikipedia page https://en.wikipedia.org/wiki/Dice_notation lists all sorts of features that would be neat but each introduces significant parsing logic. And I'm not sure how useful the extra features would be anyway (my tabletop RPG experience is limited).

I'm up for discussing the viability of different features further if you want.

**Comment by jdell64** [comment]
I actually like what you have... I ended creating a specific function for
magic missile... the only other thing i'd use that feature for would be
crits i think. Maybe rolling multiple rolls at once?

I couldn't figure it out myself... like:

```
A(xdy+z)+B
```

would be:

for(var i=0; i < A; i++){
    myRoll = droll.roll(xdy+z)
    total += myRoll['total']
}

total += B

or something like that?

## 

Richard J Tindell

Ps 102:18- "This will be written for the generation to come, That a people
yet to be created may praise the Lord."

**Comment by thebinarypenguin** [comment]
Yeah once you start throwing in parenthesis you get into mathematic formula parsing which is not something I really want to do just to generate some simple random numbers.
